### ISSUE TITLE
Support TrucksBook

### ISSUE THREAD

**Issue by Kazenin** [truckersmp-cli/truckersmp-cli#103]
is possible?

the original project devs will not support for linux, unfortunatelly

**Comment by Lucki** [comment]
The program itself works but it can't find the running ETS2.

**Comment by Kazenin** [comment]
Yes, I tried to run it on the same game prefix but no success

**Comment by LuckCrafter** [comment]
I can run the game in singleplayer (you can't see the file in the folder </.../steamapps/common/Euro\ Truck\ Simulator\ 2/bin/linux_x64/> but select it over the textbox on the bottom "eurotrucks2")

**Comment by LuckCrafter** [comment]
But I can't open the truckersmp-cli over trucksbook because the "Argument" box did't work. :-/

**Comment by Lucki** [comment]
> I can run the game in singleplayer (you can't see the file in the folder </.../steamapps/common/Euro\ Truck\ Simulator\ 2/bin/linux_x64/> but select it over the textbox on the bottom "eurotrucks2")

I guess the launcher just runs [steam://install/227300](steam://install/227300) for singleplayer which automatically launches steam and starts the linux version.
Speaking of the linux version: You're using the linux version for your tests. The multiplayer needs [the windows version](https://github.com/lhark/truckersmp-cli#game-data) to work.

**Comment by LuckCrafter** [comment]
But the Multiplayer start ETS2 over steam too (without a ets2 or steam over wine).

**Comment by LuckCrafter** [comment]
on the pfx folder are only another Settings files (the "Euro Truck Simulator 2" folder in Documents), not the complete game.

**Comment by Lucki** [comment]
I've digged a bit, generally this works but I wasn't able to accept deliveries.

* Innoextract can unpack the installer
* It needs at least `dotnet45` despite the website claiming `dotnet40` is enough
* It needs `mscoree` and `mshtml`
* All our steam checks break because their process name also includes `steam`
* The `trucksbook_64.dll` has to be in a folder `plugins` right next to the ETS2/ATS executable
* Tested and working:
  * Logging in
  * Connecting to ETS2
  * Viewing past deliveries (logbook)
  * Pushing deliveries to the website
  * Pulling assigned deliveries from the website
* Tested not working:
  * Remembering login (╯°□°)╯︵ ┻━┻
  * Accepting assigned deliveries, button does nothing. I've watched a video - there should be a save game selection after clicking
* The buttons to start the game/truckersmp are just simple shortcuts we could try to rewrite them…
* … the options are placed in the registry
* Also: It requires a game restart before every accepted delivery, seems very inconvenient

@kakurasan Any opinions? All that could be it's own wrapper but it probably has to be in the same prefix so it would make sense to include it. Maybe it's possible to make this somewhat universal to cover similar plugins?

**Comment by kakurasan** [comment]
> Accepting assigned deliveries, button does nothing. I watched a video - there should be a save game selection after clicking

If its *core* features *only partially* work even when MS .NET Framework is used, and I really want to use this client, I would use Windows for now.

I'd like to wait until this feature works with Wine/Proton. I don't think that our "launcher" program can fix or work around it.

Anyway, thanks for the useful report.

**Comment by Lucki** [comment]
Yes, I've forgot to explicitly write "if it's working correctly" which it isn't in the current state.

@Kazenin @LuckCrafter In the current state their program isn't completely functional so we won't support TrucksBook for now.

> the original project devs will not support for linux, unfortunatelly

Linux support of TrucksBook wouldn't even help, it has to run in WINE for multiplayer.

* The big showstopper here is that accepting the deliveries isn't possible. I'm not sure what they're doing there but it just doesn't happen anything.
* Another thing is the requirement of dotnet45. It would be much better if the developers would make sure their stuff is running with [mono](https://www.mono-project.com/).

**Comment by Alexithymia2014** [comment]
Hi @Lucki , how did you get TrucksBook to recognize the game running? I dropped the DLL in the plugins folder next to the exe for ATS but the client itself didn't see the game running. I did install dotnet45 in my wineprefix for TrucksBook. My small TrucksBook group do not utilize assigned deliveries so I was curious to see if I could get this working for myself in Linux. Thanks!

**Comment by Lucki** [comment]
First thing is to know if the game picked the plugin: There should be an ingame window popping up saying something with a loaded SDK.
Next thing is that the wineprefixes presumably have to be the same.
If both above points apply there should pop up new completed deliveries in the trucksbook window.

**Comment by Alexithymia2014** [comment]
> First thing is to know if the game picked the plugin: There should be an ingame window popping up saying something with a loaded SDK.
Yep I definitely get this message so that's good. 
> Next thing is that the wineprefixes presumably have to be the same.
I'm have to try this, I didn't use the same prefixes but assumed since wine isn't sandboxed it wouldn't matter haha.
> If both above points apply there should pop up new completed deliveries in the trucksbook window.
Got it, thanks! I appreciate your response! One other thing I might need to fix is that the truckersmp login doesn't show up when I launch with the wine switch rather than proton 🤔

**Comment by Lucki** [comment]
> with the wine switch rather than proton

You can still use proton with something like, please verify your paths
~~~
STEAM_COMPAT_DATA_PATH="$XDG_DATA_HOME/truckersmp-cli/Euro Truck Simulator 2/prefix/" "$XDG_DATA_HOME/truckersmp-cli/Proton/proton" run "/path/to/TB Client.exe"
~~~

**Comment by Hubok** [comment]
I realize this is an old issue now, but has anyone been able to successfully do this? I can get TrucksBook Client to open with no issues in a different prefix, and the SDK does load. However, it doesn't detect the game open.

If I try to put it in the same prefix, I can't start ETS2 or ATS after TrucksBook because Steam will think the game is open.

**Comment by Alexithymia2014** [comment]
Unfortunately I'm in the same boat, I was going to try again soon but
previously I couldn't get it to load any deliveries I had made.

**Comment by Hubok** [comment]
I was just able to get both TrucksBook and ATS going in the same prefix... but for some reason it still believes my game isn't running. Even though I got the SDK message. This thing has some weird expectations about the game.

**Comment by SKBotNL** [comment]
Still no fix for this?

**Comment by Hubok** [comment]
> Still no fix for this?

It's probably something about TrucksBook running in Wine and struggling to communicate with the game. Their app doesn't support Linux and this project really can only try to find a solution if possible.

**Comment by Lucki** [comment]
> Still no fix for this?

There's nothing to fix, it still works as described before but they now require [dotnet48 instead of dotnet45](https://trucksbook.eu/topic/8952/).

Steps to get it working:
1. Innoextract can unpack the setup
1. It needs at least `dotnet48` installed in the prefix so `wine >= 5.18` is mandatory
1. It needs `mscoree` and `mshtml` enabled
1. The `trucksbook_64.dll` has to be in a folder `plugins` right next to the ETS2/ATS executable
1. The folder `C:\users\Public\Documents\TB Client` has to be present in the prefix
1. TrucksBook has to be running before the game is starting
1. The game has an ingame popup about a loaded SDK
1. TrucksBook displays something about ETS2/ATS is running in the upper left

**Comment by SKBotNL** [comment]
> > Still no fix for this?
> 
> There's nothing to fix, it still works as described before but they now require [dotnet48 instead of dotnet45](https://trucksbook.eu/topic/8952/).
> 
> Steps to get it working:
> 
>     1. Innoextract can unpack the setup
> 
>     2. It needs at least `dotnet48` installed in the prefix so `wine >= 5.18` is mandatory
> 
>     3. It needs `mscoree` and `mshtml` enabled
> 
>     4. The `trucksbook_64.dll` has to be in a folder `plugins` right next to the ETS2/ATS executable
> 
>     5. The folder `C:\users\Public\Documents\TB Client` has to be present in the prefix
> 
>     6. TrucksBook has to be running before the game is starting in the same prefix as the game
> 
>     7. The game has an ingame popup about a loaded SDK
> 
>     8. TrucksBook displays something about ETS2/ATS is running in the upper left

Oh thanks. Ill try that.

**Comment by kallestrop** [comment]
I successfully installed Trucksbook with the steps Lucki  explained, except extraction of setup file with innoextract didn'n work, so i took TrucksBook  folder from a windows installation. 

But now since it works with truckersmp-cli, i am curious how i can make it work with ETS2 in normal singleplayer started from steam client.

I installed Trucksbook in same prefix of ETS2 singleplayer  an i can successfully start it in terminal with:

`STEAM_COMPAT_DATA_PATH="/home/user/.steam/steam/steamapps/compatdata/227300" "/home/user/.local/share/Steam/steamapps/common/Proton 6.3/proton" run "/home/user/.steam/steam/steamapps/compatdata/227300/pfx/drive_c/Program Files (x86)/TrucksBook Client/TB Client.exe"`

Now when i start the main game in Steam client, it doesn´t come up not till i close the TB Client.exe. After that, the game continue booting and starts normal.

So i can only start either Trucksbook or ETS2 but not both together.

Maybe someone here has an idea how to use both in normal singleplayer game.

**Comment by Lucki** [comment]
I think steam is using `waitforexitandrun` internally instead of `run` which would explain that behavior. The simplest thing would be using `--singleplayer` with `truckersmp-cli`.

**Comment by kallestrop** [comment]
Ah, yes that is an option. I had in mind truckersmp-cli with option `--singleplayer` is always without traffic. But now i remember i set `g_traffic "0"` in config.cfg long time ago. Thanks for the hint.

**Comment by Kazenin** [comment]
> > Still no fix for this?
> 
> There's nothing to fix, it still works as described before but they now require [dotnet48 instead of dotnet45](https://trucksbook.eu/topic/8952/).
> 
> Steps to get it working:
> 
>     1. Innoextract can unpack the setup
> 
>     2. It needs at least `dotnet48` installed in the prefix so `wine >= 5.18` is mandatory
> 
>     3. It needs `mscoree` and `mshtml` enabled
> 
>     4. The `trucksbook_64.dll` has to be in a folder `plugins` right next to the ETS2/ATS executable
> 
>     5. The folder `C:\users\Public\Documents\TB Client` has to be present in the prefix
> 
>     6. TrucksBook has to be running before the game is starting in the same prefix as the game
> 
>     7. The game has an ingame popup about a loaded SDK
> 
>     8. TrucksBook displays something about ETS2/ATS is running in the upper left

Unfortunately it didn't work here. Could anyone record a more detailed video about this installation?

**Comment by Alexithymia2014** [comment]
I'm in the same boat, I can get it to detect the game but deliveries are
not recorded.

**Comment by kallestrop** [comment]
To get Trucksbook working was a bit tricky for me too. I tried several times installing it until it suddenly works. 

I think most important is to use at least wine version >= 6.3 so launching truckersmp-cli with proton 6.3 is required.

If dotnet48 is installed with wine 6.3 in game prefix and you start truckersmp-cli with default proton 5.10,  i think it breaks something and you have to delete the prefix.

At least for me, installation worked with wine-staging 6.8 as system wide wine version and running game with proton 6.3

I installed dotnet48 with:
`WINEPREFIX=~/.local/share/truckersmp-cli/Euro\ Truck\ Simulator\ 2/prefix/pfx winetricks --force dotnet48`

Added `mscoree` and `mshtml` in the library section of winecfg:
`WINEPREFIX=~/.local/share/truckersmp-cli/Euro\ Truck\ Simulator\ 2/prefix/pfx winecfg`

**Comment by Kazenin** [comment]
Does the trucksbook register your deliveries made by truckersmp-cli ?

*Greyson Farias da Silva*
Tecnólogo em Análise e Desenvolvimento de Sistemas
Técnico em Operação de redes - CREA/AC 9329TD
Eu prefiro receber documentos em ODF
<http://pt.wikipedia.org/wiki/OpenDocument>.
Baixe o Fedora e seja livre: https://getfedora.org
Comunidade Linux do Acre: http://acrelinux.org




Em seg., 7 de jun. de 2021 às 12:44, kallestrop ***@***.***>
escreveu:

**Comment by kallestrop** [comment]
1.) Start Trucksbook from terminal:

`STEAM_COMPAT_DATA_PATH="~/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix/" "~/.local/share/truckersmp-cli/Proton/proton" run "~/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/Program Files (x86)/TrucksBook Client/TB Client.exe"`

2.) Start truckersmp-cli from a second terminal:

`truckersmp-cli --ets2 --start --proton --enable-d3d11 --activate-native-d3dcompiler-47`

**Comment by kallestrop** [comment]
When using Proton 6.3-5-rc1 from the Steam "next" branch you get following error when starting with `run`:

```
Traceback (most recent call last):
  File "/home/user/.local/share/truckersmp-cli/Proton/proton", line 1030, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/user/.local/share/truckersmp-cli/Proton/proton", line 859, in init_session
    g_compatdata.setup_prefix()
  File "/home/user/.local/share/truckersmp-cli/Proton/proton", line 483, in setup_prefix
    steamdir = os.environ["STEAM_COMPAT_CLIENT_INSTALL_PATH"]
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'STEAM_COMPAT_CLIENT_INSTALL_PATH'
```

You have to start TB Client.exe with `runinprefix`, so the complete line is:

`STEAM_COMPAT_DATA_PATH="/home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix/" "/home/user/.local/share/truckersmp-cli/Proton/proton" runinprefix "/home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/Program Files (x86)/TrucksBook Client/TB Client.exe"`

**Comment by Lucki** [comment]
> You have to start TB Client.exe with `runinprefix`

Nah, the actual error is directly mentioned: `KeyError: 'STEAM_COMPAT_CLIENT_INSTALL_PATH'`
This error gets solved by setting the environment variable `STEAM_COMPAT_CLIENT_INSTALL_PATH`.
Proton 6.3+ seems to check for this now instead of silently accepting it missing and failing in later parts, causing https://github.com/truckersmp-cli/truckersmp-cli/issues/34#issuecomment-620279525.

`runinprefix` however seems like a more recent addition which skips the setup part that requires the environment variable to be set. So this is a viable alternative for this use case.
